baseURL = "https://navinkarkera.github.io/"
languageCode = "en-us"
theme = "sada"
disableKinds = ["taxonomy", "taxonomyTerm"]

[params]
name = "Navin Karkera"
title = "Resume"
author = "Navin Karkera"
description = "Full Stack Python Developer"
copyright = "Custom copyright message"
theme = "dark" # `dark` or `light`
useResources = false

# Profile section
[params.profile]
name = "Navin Karkera"
photo = "images/profile.jpg"
email = "navinkarkera@disroot.org"
mobile = "+91 8655861306"

# Section for links to social websites
[params.social]
title = "Links"

[[params.social.list]]
icon = "fab fa-linkedin-in"
url = "https://www.linkedin.com/in/navin-karkera-407957a0/"
title = "LinkedIn"

[[params.social.list]]
icon = "fab fa-github"
url = "https://github.com/navinkarkera"
title = "GitHub"

[[params.social.list]]
icon = "fab fa-gitlab"
url = "https://gitlab.com/navinkarkera"
title = "Gitlab"

[[params.social.list]]
icon = "fab fa-reddit"
url = "https://www.reddit.com/user/navinkarkera"
title = "Reddit"

[[params.social.list]]
icon = "fas fa-file-download"
url = "Resume.pdf"
title = "Download PDF"

# Education section
[params.education]
title = "Education"

[[params.education.list]]
degree = "Bachelor of Engineering"
college = "University of Mumbai"
dates = "2011 - 2014"
field = "Electronics and Telecommunication"

[[params.education.list]]
degree = "Diploma"
college = "Maharashtra State Board of Technical Education"
dates = "2008 - 2011"
field = "Industrial Electronics"

# Languages section
[params.language]
title = "Languages"

[[params.language.list]]
language = "English"
level = "Fluent"

[[params.language.list]]
language = "Hindi"
level = "Fluent"

# Interests section
[params.hobbies]
title = "Hobbies"

[[params.hobbies.list]]
interest = "Travelling"

[[params.hobbies.list]]
interest = "Music"

[[params.hobbies.list]]
interest = "Reading"

[params.aboutme]
description = """
I am a software developer working as a Python Automation Expert in UBS, automating different process using Python and web technologies.

In my own time, I like to learn new technologies like Rust, Go and customize my GNU/Linux setup. I use `Neovim` as my main editor, and like to improve my workflow with it.
"""


# Experiences section
[params.experiences]
title = "Experiences"

[[params.jobs.list]]
position = "Authorized Officer"
dates = "Jan 2018 - *Present*"
link = "https://www.ubs.com/"
company = "UBS"
details = """
*Core technologies*: `Python, VueJs and GNU/Linux`

Serving as a core member of the team working on building an automated model
documentation solution used by the whole division, while handling multiple side
projects individually such as building web applications, automating ETL like
processes and reporting solutions for different teams.

*Key Achievements:*

- Developing major features for division wide solution for documentation
  automation (`DocKit`) ranging from `JupyterLab plugins` to **smart merging**
  of notebooks. Using `pandoc` to convert from one format to another i.e.
  jupyter notebooks to markdown to LaTex and Jinja templates to dynamically
  generate LaTex files, we are automating the process for model documentation,
  confirmation and validation. I am involved in planning, development,
  documentation and working with clients to onboard the tool.

- Developed reporting solution for Risk Weighted Assets(RWA) using
  `Python/Pandas/Flask` which greatly reduced cost and time to generate
  reports which is sent to FED Regulators.

- Worked in Agile Methodology to develop static sites and dynamic web
  applications using tools like `FastAPI`, `VueJs`, `NLTK/Spacy` to build smart
  solutions like google like FAQ, shares reporting to Regulators etc.

- Built soultions using `Python Airflow`, `Pandas` etc. to automate ETL like
  process involving Chief Risk Officers which included reporting of shorfalls,
  violations, ECN limits etc. These were recognized as a major help for the bank
  in pandemic times.

- Got a chance to learn about data processing, training machine learning models
  while working **data qualtity** project which was an attempt to detect data
  qualtity issues in data received by other banks which was manually
  scanned by Risk Officers.

- Handled multiple deployments in GNU/Linux servers hosted on Azure. Secured
  the web services using tools like `systemd`, `nginx`. Automated deployments
  using bash scripts, python doit wherever possible.

- Conducted Python Workshops.

- Won a hackathon and helped in conducting another hackathon.

- _**Promoted to Authorized Officer from Employee position.**_.

"""

[[params.jobs.list]]
position = "Senior Software Developer"
dates = "Feb 2017 - Jan 2018"
link = "https://www.bankofamerica.com/"
company = "Bank of America"
details = """
*Core technologies*: `Python, SQL`

Worked for Market Risk team solving architectural design issues and code level
issues. Built complete systems to automate a manual process and also helped
migrating complete projects from Java to Python platform.

*Key Achievements:*

- Initiated a project called Chat-Bot, built it from scratch using NLTK and
  Django rest framework, also integrated it with Skype for Business.

"""

[[params.jobs.list]]
position = "Lead Developer"
dates = "Feb 2015 - Feb 2017"
link = "https://dff.org.in/"
company = "Digital Freedom foundation"
details = """
*Core technologies*: `Python, Postgres, Docker and GNU/Linux`

Started my career as a software developer in a start-up where I worked on
everything related to a web application, from designing, development to
deployment. The project was a Free and open source accounting and inventory
software called GNUKhata. Built it from scratch using Pyramid pylons framework,
bootstrap, JQuery, Postgres, Docker etc.

*Key Achievements:*

- Learnt about programming in Python and web technologies the most in the first
  two years and contributed extensively to the project GNUKhata.

- Grasped concepts of containerized environments in the process of making
  deployment of GNUKhata platform independent using Docker.

"""

# Projects section
[params.projects]
title = "Projects"

[[params.projects.list]]
title = "Dockit"
url = "#"
description = "JupyterLab based documentation solution for building Model development/validation/confirmation reports using Jinja templates and LaTex"

[[params.projects.list]]
title = "RWA"
url = "#"
description = "Web application to generate multiple reports to be sent to Feds"

[[params.projects.list]]
title = "GNUKhata"
url = "https://gnukhata.in/"
description = "Free & Open Source accounting and inventory software"

# Skills section
[params.skills]
title = "Skills"

[[params.skills.list]]
skill = "Python, Pandas, FastAPI"
skillrating = 95 # out of 100

[[params.skills.list]]
skill = "Git"
skillrating = 95 # out of 100

[[params.skills.list]]
skill = "Javascript, VueJs, working knowledge of CSS"
skillrating = 90

[[params.skills.list]]
skill = "Airflow/Prefect"
skillrating = 80

[[params.skills.list]]
skill = "Sql, PostgresSQL"
skillrating = 80

[[params.skills.list]]
skill = "Flask/Django"
skillrating = 60 # out of 100

[[params.skills.list]]
skill = "Rust"
skillrating = 40 # out of 100

